# Generated by Django 4.2.6 on 2023-10-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=250)),
                ("photo", models.ImageField(upload_to="photos/%Y%m%d/")),
                ("facebook_link", models.URLField(default=False)),
                ("twitter_link", models.URLField(default=False)),
                ("google_plus_link", models.URLField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
