# Generated by Django 4.2.6 on 2023-10-28 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 10, 29, 0, 4, 2, 968062)
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="doors",
            field=models.CharField(
                choices=[("2", "2"), ("3", "3"), ("4", "4"), ("5", "5"), ("6", "6")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="car", name="fuel_type", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="car",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
